spring.datasource.url=jdbc:mysql://localhost:3308/banking_db
spring.datasource.username=root
spring.datasource.password=Banking123!A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
app.jwt.secret=THIS_IS_A_LONG_RANDOM_SECRET_AT_LEAST_32_CHARS_123456
app.jwt.expiration-minutes=120
